services:

  ibkr_gateway:
    restart: always
    build:
      context: ./ibkr_gateway
    networks:
      - trader

  webapp:
    build:
      context: ./webapp
    ports:
      - "5056:5056"
    networks:
      - trader

networks:
  trader:
