services:

  ibkr_gateway:
    build:
      context: ./ibkr_gateway
    ports:
      - "5055:5055"
      - "5056:5056"
    networks:
      - trader
    environment:
      IBKR_ACCOUNT_ID: "U1234567"

networks:
  trader:
