services:

  ibkr_gateway:
    build:
      context: ./ibkr_gateway
      network: host
      args:
        - CERTBOT_EMAIL=david.a.gorski@gmail.com
        - DOMAIN_LIST=qa-dg-quant-trader.com
    restart: always
    ports:
      - "5055:5055"
      - "5056:5056"
      - "80:80"
      - "443:443"
    environment:
      IBKR_ACCOUNT_ID: "U1234567"
    volumes:
      - ./nginx/default_qa.conf:/etc/nginx/conf.d/default.conf
      - letsencrypt:/etc/letsencrypt
    networks:
      - trader

volumes:
  letsencrypt:

networks:
  trader:
